### ISSUE TITLE
Define common interface for sensors

### ISSUE THREAD

**Issue by daneel0livaw** [SzFMV2018-Osz/AutomatedCar-B#131]
**GetWorldObjectsInArea method**
- [ ] input: triangle vertices
- [ ] output: list of world objects
- [ ] makes difference between collidable and non collidable objects

**Comment by AllStarzZZ** [comment]
Ez 3db integerből(x1, x2, x3), hogyan fog megadni egy háromszöget egy két dimenziós térben?

**Comment by dezsi96** [comment]
> 
> 
> Ez 3db integerből(x1, x2, x3), hogyan fog megadni egy háromszöget egy két dimenziós térben?

Hát az egyik opció az lehet, hogy a 32 bit-es integer első 16 bitje adja az x-et a második pedig az y-t. :D
Na de viccet félretéve, ezt jól benéztük, elnézést kérünk. Köszi az észrevételt, megpróbáljuk mielőbb módosítani.
