### ISSUE TITLE
Implement base class for sensors

### ISSUE THREAD

**Issue by daneel0livaw** [SzFMV2018-Osz/AutomatedCar-B#132]
GetWorldObjectsInArea method

**Comment by daneel0livaw** [comment]
Sziasztok! A szenzor csak azokat a tárgyakat érzékelje adott területen belül, ami teljes terjedelmével bent van, vagy olyanokat is, amiknek csak egy része?

**Comment by pintergreg** [comment]
@daneel0livaw Akkor is ha csak egy része, ez később egyes csapatoknak fontos lesz/lehet.

**Comment by daneel0livaw** [comment]
Változás: ISensor interfészt minden szenzor osztály magának fogja implementálni, és egyben leszármazik majd a SensorBase ősosztályból.
