### ISSUE TITLE
Koordinátarendszerről egyeztetni a világmodelt kezelő csapattal

### ISSUE THREAD

**Issue by rdani95** [SzFMV2018-Osz/AutomatedCar-B#14]

**Comment by Horti94** [comment]
Kapcsolat felvéve, megbeszélés alatt.

**Comment by kislevi94** [comment]
@rdani95 , @Horti94 
Kérdései alapján felvettük a kapcsolatot újra a Team-B1 csapattal, hogy a végső egyeztetések a Sprint 1 lezárása tökéletesen megtörténjen.

> Milyen módon kapjuk meg a dolgokat (static, dinamic lista és az automatedCar)?
> Milyen módon dolgoztok, mert a world object nem lett átírva (ami alapból meg lett adva) ahogy látjuk, így nem tudjuk, hogy milyen módon változtattatok a dolgokon, hogy tudjuk, miképpen fognak a megjelenítendő elemek és adataik hozzánk kerülni?

Ha van bármi más kérdés még, azt jelezzétek nekem vagy @Kr1szace -nek.

Amint megérkezik a válasz, közzé teszem.
