### ISSUE TITLE
Dinamikus objektumok megjelenítése

### ISSUE THREAD

**Issue by rdani95** [SzFMV2018-Osz/AutomatedCar-B#17]
- [x] Az irányított autó mindig középen marad
- [ ] Egyéb mozgó objektumok helyesen mozognak
- [ ] Mozgó objektumok helyesen fordulnak

**Comment by ravaszla** [comment]
Ez egy baromi absztrakt és generikus taszk - gondoljátok végig, hogy is fog ez történni, milyen osztályokon és mechanizmusokon keresztül, és azoknak az elkészítése lehet taszk.
