### ISSUE TITLE
Dod elemzése, funkciók, input/output adatok vizsgálata

### ISSUE THREAD

**Issue by ral2bp** [SzFMV2018-Osz/AutomatedCar-B#31]
DoD:
- taskok meghatározva az implementálandó elemek alapján

**Comment by pintergreg** [comment]
Dod elemzése? Mivel minden tasznak van DoD-ja, így fura, szerintem most a User Story DoD-járól van szó.
Ezt egyébként miért csak egy ember csinálja? Mi a munka kimenete?

**Comment by kovacsistvan1** [comment]
Ez egy kezdetleges elgondolás volt.  Törlöm a task -ot
