### ISSUE TITLE
Erők összegzése

### ISSUE THREAD

**Issue by adakiss** [SzFMV2018-Osz/AutomatedCar-B#38]
A kiszámolt erők összegzése és felrakása a busszra. 

- [ ] Vissza tartó erők összegzése
- [ ] Összegzet lassító erők beiktatása a mozgás vektorba
- [ ] Tollatásnál neggatív mozgás vektor
- [ ] Előre menet
- [ ] Kanyarodás kivezetése a buszra

**Comment by pintergreg** [comment]
- Mihez képest tényleges?
- Van nem tényleges is?
- Minek pozíciója?
- Mit jelent a meghatározás?
- Ez egy alibi taszk? :stuck_out_tongue:
