### ISSUE TITLE
Kép frissítéskori "rezgésének" megszüntetése.

### ISSUE THREAD

**Issue by rdani95** [SzFMV2018-Osz/AutomatedCar-B#43]
Frissítéskor minden felrajzolt kép rezeg, mintha nem egyszerre, hanem egymás után frissülnének.

DoD:

- [x] a BufferedImage-k egyszerre frissülnek
- [x] a teljes kép "összefüggő", nem részenként rajzolódnak újra.
- [x] statikus és mozgó objektumoknál is jól működik

**Comment by rdani95** [comment]
DoD:

- [ ] a BufferedImage-k egyszerre frissülnek
- [ ] a teljes kép "összefüggő", nem részenként rajzolódnak újra.
- [ ] statikus és mozgó objektumoknál is jól működik

**Comment by rdani95** [comment]
> A GitHub (azt hiszem) csak akkor kezeli jól a DoD-t, ha az issue leírásában van. (áthelyeztem)
> De ez csak egy kis apró megjegyzés a GH trükkök kapcsán.

Értem, köszi!

**Comment by rdani95** [comment]
Megoldás: https://docs.oracle.com/javase/tutorial/extra/fullscreen/doublebuf.html

**Comment by kislevi94** [comment]
Review:

- [ ] Krisz
- [ ] Levi
