### ISSUE TITLE
Motor viselkedésének modellezése

### ISSUE THREAD

**Issue by adakiss** [SzFMV2018-Osz/AutomatedCar-B#45]
A motor viselkedésének lemodellezése, vagyis a fordulatszámának meghatározása és a fordulatszám alapján az automata váltás megvalósítása.

Definiton of done:
- [x] Az autó motorjának modellezése
- [x] Az autó sebessége és a kerekének sugara alapján a motor fordulatszámának a meghatározása
- [x] Automata váltás megvalósítása magasabb fokozatba, amennyiben a megadott határérték fölé emelkedik a fordulatszám
- [x]  Automata váltás megvalósítás alacsonyabb fokozatba, amennyiben a megadott határérték alá csökken a fordulatszám

**Comment by pintergreg** [comment]
Ez egy egészen szépen kifejtett issue (a többihez képest).
