### ISSUE TITLE
TransformRotate

### ISSUE THREAD

**Issue by Horti94** [SzFMV2018-Osz/AutomatedCar-B#46]
Az objektumok pozíció és arány helyes kirajzolása mellett azok transzformációját is implementálni kell a kirajzolás előtt.

**Comment by pintergreg** [comment]
@Horti94 Pontosan mit értesz azon, hogy a transzformációt implementálod?

- alkalmazod az (elforgatás) implementációt az objektumra
- vagy implementálsz egy elforgatást megvalósító metódust?
- egyéb

**Comment by kislevi94** [comment]
Review:

- [ ] Levi
