### ISSUE TITLE
Fék erő meghatározása a fékpedál állása alapján.

### ISSUE THREAD

**Issue by bex1111** [SzFMV2018-Osz/AutomatedCar-B#48]
Fék erő meghatározása a fékpedál állása alapján.

Dod:

- [x] fék erő vektor meghatározása

**Comment by pintergreg** [comment]
@SzFMV2018-Osz/team-b4 Az #51 -ben kifejtett észrevételek ide is érvényesek, mivel az is a tiétek nem duplikálom.
