### ISSUE TITLE
IDE telepítése

### ISSUE THREAD

**Issue by matejasko** [SzFMV2018-Osz/AutomatedCar-B#5]
Install IntelliJ IDEA
- [x] Riery
- [x] norbi38
- [x] porkolabgergo
- [x] matejasko
- [x] szviktor94

**Comment by pintergreg** [comment]
A taszk felelőse a teljes csapat (nem kizárt, hogy van ilyen), de hogyan oldjátok meg azt, hogy X telepítette, de Y még nem? Milyen oszlopban van ilyenkor a a taszk?
