### ISSUE TITLE
Surlódási erő kiszámítása

### ISSUE THREAD

**Issue by valkarion** [SzFMV2018-Osz/AutomatedCar-B#51]
Visszaható erő vektor meghatározása

**Comment by pintergreg** [comment]
Úgy tűnik, hogy ez az issue csak ötlet szintig jutott. Látom, hogy csak 1 napos, de még így is nagyon gyér a kifejtettsége. Én is szoktam olyat, hogy ha jön egy ötlet, akkor egy „üres” issue-ban rögzítem, aztán a következő iterációban specifikálom részleteiben, hogy mit akarok csinálni  (határidőtől függő, de akár napokkal később is történhet). Majd jöhet az implementáció....

Jelen esetben az a probléma, hogy majdnem két hete ismeretes, hogy szükség van ilyen erőkre. Ez a múlt hétre is szűkös lett volna, most már min. ott kellene tartani, hogy részletes, implementáció szintű kidolgozása van a felbontott feladatoknak.

Segítő kérdések:

- Milyen formában (osztállyal) kerül reprezentálásra az „erő vektor”?
- Pontosan miből (mely osztály mely adattagjaiból) és milyen képlettel számoltok súrlódási erőt?
- Hogyan aggregálod a súrlódási erőt a légellenállással (#49)?
    - ha már külön ilyen is van
- Milyen formában fejtik kik hatásukat ezek a lassító erők az autóra?
- Egyáltalán milyen módon van mozgatva az autó?
    - akár ide lehetne linkelni az azt specifikáló issue-t...

**Comment by kovacsistvan1** [comment]
Súrlódási erő vektor meghatározása:

DoD:

- [ ] Matematikai függvény meghatározása

- [ ] Tesztesetek definiálása

- [ ] Tesztesetek validálása
