### ISSUE TITLE
Hierarchia megtervezése

### ISSUE THREAD

**Issue by matejasko** [SzFMV2018-Osz/AutomatedCar-B#7]
- [x] Osztály hierarchia megtervezése (UML Osztály Diagram)

**Comment by Riery** [comment]
![42347348_232321590974831_5172850674202836992_n](https://user-images.githubusercontent.com/18727497/46099343-d1106c80-c1c6-11e8-87a2-488c2f21c8c6.jpg)

Kezdetleges vázlat.

**Comment by matejasko** [comment]
![42532583_678810635852608_4973857791337824256_n](https://user-images.githubusercontent.com/43233673/46099576-6ca1dd00-c1c7-11e8-99c6-65f4376af9c9.jpg)

**Comment by matejasko** [comment]
Vizualizációs csapattal való egyeztetés után, osztályhierarchia újratervezve.
+ Scene osztály: Pályát reprezentálja, vizualizációs csapat kérésére.
+ ControllableCar a saját "player-charactert" reprezentálja, az esetelges + metódusok stb. miatt kapott külön osztályt.

![copy of blank diagram](https://user-images.githubusercontent.com/43233673/46164515-793d3880-c28e-11e8-8f16-fcb9b2f7e86a.jpeg)

**Comment by matejasko** [comment]
Object ősosztály átnevezése.

![copy of blank diagram](https://user-images.githubusercontent.com/43233673/46164930-91fa1e00-c28f-11e8-9a4e-cf0cde2c8c85.jpeg)

**Comment by matejasko** [comment]
Rename WorldObject --> ParentObject
![copy of blank diagram](https://user-images.githubusercontent.com/43233673/46431589-7ccc3600-c74c-11e8-9412-42e20de68af6.jpeg)

**Comment by matejasko** [comment]
Transform m11, m12, m21, m22 int --> double
![copy of blank diagram](https://user-images.githubusercontent.com/43233673/46436966-8bb9e500-c75a-11e8-8e3e-d61c6eebb44f.jpeg)

**Comment by matejasko** [comment]
![copy of blank diagram](https://user-images.githubusercontent.com/43233673/46586453-12cecc00-ca7f-11e8-93a3-ecec98b03a18.jpeg)

**Comment by matejasko** [comment]
![copy of blank diagram](https://user-images.githubusercontent.com/43233673/46631360-73c1d700-cb47-11e8-85f1-a25aba9c6874.jpeg)

**Comment by matejasko** [comment]
![hierarchy](https://user-images.githubusercontent.com/43233673/47106646-73ac9000-d247-11e8-98c3-84b794acfeb8.jpeg)
