### ISSUE TITLE
Objektumok beolvasása a test_world.xml-ből

### ISSUE THREAD

**Issue by matejasko** [SzFMV2018-Osz/AutomatedCar-B#9]
A test_world.xml beolvasása egy File objektumba, fájl objektum átkonvertálása egy dokumentumba amiből ki lehet nyerni az xml-ben lévő adatokat struktúrálva
- [x] A beolvasás megvalósítása az XML alapján

**Comment by pintergreg** [comment]
- Melyik fájlból kell olvasni?
- Mit kell belőle kiolvasni?
- Mibe kell azt beolvasni?

A taszk nagyjából azt mondja, hogy egy általános fájl olvasás metódust kell implementálni. Minden kulturált nyelvben van ilyen készen...
